name: Wait for PR
inputs:
  prNumber:
    description: 'Number of the PR to wait for'
    required: true
  repo:
    description: 'Repo'
    required: true
  owner:
    description: 'Owner'
    required: true
  githubToken:
    description: 'Github token'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    REPO: ${{ inputs.repo }}
    OWNER: ${{ inputs.owner }}
    PR_NUM: ${{ inputs.prNumber }}
    GITHUB_TOKEN: ${{ inputs.githubToken }}