name: use my action
on:
  push:
    branches:
      - main
    paths:
      - 'manifests/**'

jobs:
  promote_to_test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Promote files to test1
        run: |
          set -x

          DIRS_CHANGED=$(git diff --dirstat=files,0 HEAD~1 | sed 's/^ [0-9.% ]*//g' | grep manifests)
          echo "Dirs changed $DIRS_CHANGED"

          if [ `echo $DIRS_CHANGED | wc -l | awk '{print $1}'` -ge "1" ]; then
            echo "only 1 dir please"
            exit 1
          fi;

          cp -r $(DIRS_CHANGED) test/test1/
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Promote to test" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - id: pr
        run: echo "::set-output name=prNumber::1"
        shell: bash
      - name: My first step
        uses: ./.github/actions/wait-for-pr
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prNumber: ${{ steps.pr.outputs.prNumber }}
          repo: github-actions-gitops-promotion
          owner: janakerman
